import { Card } from '../../models/card';

export interface CardsState {
  cards: Card[];
  loading: boolean;
}

export enum CardsActionTypes {
  CARDS_LOAD_REQUEST = 'CARDS_LOAD_REQUEST',
  CARDS_LOAD_SUCCESS = 'CARDS_LOAD_SUCCESS',
  CARDS_LOAD_FAILURE = 'CARDS_LOAD_FAILURE',

  CARD_LIKE_REQUEST = 'CARD_LIKE_REQUEST',
  CARD_LIKE_SUCCESS = 'CARD_LIKE_SUCCESS',
  CARD_LIKE_FAILURE = 'CARD_LIKE_FAILURE',

  CARD_UNLIKE_REQUEST = 'CARD_UNLIKE_REQUEST',
  CARD_UNLIKE_SUCCESS = 'CARD_UNLIKE_SUCCESS',
  CARD_UNLIKE_FAILURE = 'CARD_UNLIKE_FAILURE',

  CARD_REMOVE_REQUEST = 'CARD_REMOVE_REQUEST',
  CARD_REMOVE_SUCCESS = 'CARD_REMOVE_SUCCESS',
  CARD_REMOVE_FAILURE = 'CARD_REMOVE_FAILURE',
}
